/*
 * Ski Data API for NEU Seattle distributed systems course
 * An API for an emulation of skier managment system for RFID tagged lift tickets. Basis for CS6650 Assignments for 2019
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.model.LiftRide;
import io.swagger.client.model.SkierVertical;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import java.util.Arrays;
import java.util.List;


/**
 * API tests for SkiersApi
 */
@Ignore
public class SkiersApiTest {

    private final SkiersApi api = new SkiersApi();

    @Before
    public void setup() {
        final ApiClient apiClient = api.getApiClient();
        apiClient.setBasePath("http://localhost:8080");
    }

    /**
     * get ski day vertical for a skier
     *
     * get the total vertical for the skier for the specified ski day
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSkierDayVerticalTest() throws Exception {
        Integer resortID = 123;
        String seasonID = "null";
        String dayID = "null";
        Integer skierID = 456;


        Integer response = api.getSkierDayVertical(resortID, seasonID, dayID, skierID);

        System.out.println(response);

        // TODO: test validations
    }
    /**
     * get the total vertical for the skier for specified seasons at the specified resort
     *
     * get the total vertical for the skier the specified resort. If no season is specified, return all seasons
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSkierResortTotalsTest() throws Exception {
        Integer skierID = 123;
        List<String> resort = Arrays.asList("123", "456");
        List<String> season = Arrays.asList("aaa", "bbb");
        SkierVertical response = api.getSkierResortTotals(skierID, resort, season);

        System.out.println(response);

        // TODO: test validations
    }
    /**
     * write a new lift ride for the skier
     *
     * Stores new lift ride details in the data store
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void writeNewLiftRideTest() throws Exception {
        LiftRide body = new LiftRide().time(123).liftID(456);
        Integer resortID = 123;
        String seasonID = "aaa";
        String dayID = "bbb";
        Integer skierID = 567;

        api.writeNewLiftRide(body, resortID, seasonID, dayID, skierID);

        // TODO: test validations
    }
}
